export const CHECK_VALIDITY_EMAIL = "CHECK_VALIDITY_EMAIL";
export const CHECK_VALIDITY_USERNAME = "CHECK_VALIDITY_USERNAME";
export const CHECK_VALIDITY_PASSWORD = "CHECK_VALIDITY_PASSWORD";
export const CHECK_VALIDITY_CONFIRM = "CHECK_VALIDITY_CONFIRM";
export const CHECK_VALIDITY_EMAIL_LOGIN = "CHECK_VALIDITY_EMAIL_LOGIN";
export const CHECK_VALIDITY_PASSWORD_LOGIN = "CHECK_VALIDITY_PASSWORD_LOGIN";
export const UPDATE_INPUT = "UPDATE_INPUT";
export const ERROR = "ERROR";
export const UPDATE_INPUT_LOGIN = "UPDATE_INPUT_LOGIN";
export const ERROR_LOGIN = "ERROR_LOGIN";
export const CLICKED = "CLICKED";
export const CLICKED_LOGIN = "CLICKED_LOGIN";
export const UPDATE_CONVERTER_INPUT = "UPDATE_CONVERTER_INPUT";
export const UPDATE_CONVERTER_OUTPUT = "UPDATE_CONVERTER_OUTPUT";
export const CHECK_VALIDITY_SYMBOLS_CONVERTER =
  "CHECK_VALIDITY_SYMBOLS_CONVERTER";
export const CHECK_VALIDITY_SPACE_CONVERTER = "CHECK_VALIDITY_SPACE_CONVERTER";
export const CHECK_VALIDITY_ENGLISH_CONVERTER =
  "CHECK_VALIDITY_ENGLISH_CONVERTER";
export const UPDATE_LANG_CONVERTER = "UPDATE_LANG_CONVERTER";
export const SET_LANGUAGES_CONVERTER = "SET_LANGUAGES_CONVERTER";
export const CHANGE_CODE_TYPE = "CHANGE_CODE_TYPE";
export const RESET_ALL_ERRORS = "RESET_ALL_ERRORS";
export const CHECK_VALIDITY_DIVISION_CONVERTER =
  "CHECK_VALIDITY_DIVISION_CONVERTER";
export const CHECK_VALIDITY_TYPE_CONVERTER = "CHECK_VALIDITY_TYPE_CONVERTER";
export const SET_DECODE_ERROR = "SET_DECODE_ERROR";
